### ISSUE TITLE
请教一下，Tab页面内容之间翻页的过渡透明也可以用这个思路实现？

### ISSUE THREAD

**Issue by chowaikong** [wuyexiong/WechatLikeBottomTabUI#2]
微信除了底部tab是翻页渐变，上面的页面内容也是翻页透明渐变的，请问是不是也可以用这个思路来实现？如果不是，请问可以用什么方法实现？谢谢。

**Comment by wuyexiong** [comment]
可以参考这个项目
https://github.com/ToxicBakery/ViewPagerTransforms

原理都是一样的. 都是基于ViewPager中onPageScrolled(int position, float offset, int offsetPixels) 滑动参数的变化来实现的

**Comment by chowaikong** [comment]
好的，感谢指导。
